# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true #removed per https://github.com/poole/lanyon/issues/124#issuecomment-155645090

# Setup
title:            CSX
tagline:          'ShortName'
description:      'Full Course Catalog Name'
url:              
baseurl:          /

author:
  name:           'Nery Chapeton-Lamas'
  url:            https://profe.github.io

plugins:          [jekyll-paginate]
paginate:         5
paginate_path:    "page:num" #added per https://github.com/poole/lanyon/issues/124#issuecomment-155645090

# Custom vars
themecolor:       'theme-base-0e'
version:          2.1.0

github:
  repo:           https://github.com/MiraCostaCS/CourseTemplate #replace this with specific coruse repo
