# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
#relative_permalinks: true #removed per https://github.com/poole/lanyon/issues/124#issuecomment-155645090

# Setup
course: CSX
title: "full course catalog name"
description: "course catalog description"
cor: "COR link"
logo: "logo link, make sure its in assets folder"
context: "context info here"

last-modified-at:
  date-format: "%m-%d-%Y"
url:
baseurl: /csX

author:
  name: "Nery Chapeton-Lamas"
  url: https://profe.github.io

plugins:
  - jekyll-paginate
  - jekyll-last-modified-at
paginate: 5
paginate_path: "page:num" #added per https://github.com/poole/lanyon/issues/124#issuecomment-155645090

# Custom vars
themecolor: "theme-base-0c"
version: 2.1.0

github:
  repo: https://github.com/MiraCostaCS/CourseTemplate
